# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "user_registration" ("uid" BIGINT NOT NULL PRIMARY KEY,"myName" VARCHAR NOT NULL,"organization_name" VARCHAR NOT NULL,"organization_phone" VARCHAR NOT NULL,"organization_email" VARCHAR NOT NULL,"experience" INTEGER NOT NULL,"role" VARCHAR NOT NULL,"why_participate" VARCHAR NOT NULL,"what_tools" VARCHAR NOT NULL);
create table "Sessions" ("Id" VARCHAR NOT NULL PRIMARY KEY,"uid" BIGINT NOT NULL,"data" VARCHAR NOT NULL,"timeStamp" BIGINT NOT NULL);
create table "user_info" ("uid" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"given_name" VARCHAR NOT NULL,"family_name" VARCHAR NOT NULL,"email" VARCHAR NOT NULL,"registered" BOOLEAN NOT NULL,"ipythonUrl" VARCHAR NOT NULL,"cluster_id" VARCHAR,"secret" VARCHAR);
create table "white_list" ("uid" BIGINT NOT NULL PRIMARY KEY,"email" VARCHAR NOT NULL);

# --- !Downs

drop table "user_registration";
drop table "Sessions";
drop table "user_info";
drop table "white_list";

