easy_install -U distribute
pip install numpy
pip install scipy
pip install sympy
pip install nltk
pip install pyzmq
pip install jinja2
pip install tornado
pip install mrjob
pip install matplotlib
pip install ipython
