#!/bin/sh

# If program started with 'restart', then begin at the beginning, otherwise pick up with the last one worked on.
Restart=${1:-NO}
Restart=${Restart^^}
ProgramName=$(basename $0)
StatusFile=.$ProgramName

if [ "$Restart" == "-H" -o "$Restart" == "--HELP" ]; then
    echo Program to edit the scala documentation content and the associated .rst files.
    echo Enter \"$ProgramName RESTART\" to go through all the files,
    echo otherwise the program will resume where it last was.
    echo Program generates the file \"$StatusFile\" to keep track.
    echo Quit the editor with the command ':cq' to stop processing files.
else
    if [ "$Restart" == "RESTART" ]; then
        Last=None
    elif [ "$Restart" != "NO" ]; then
        Last=$1
    else
        if [ -e $StatusFile ]; then
            Last=$(cat $StatusFile)
        else
            Last=None
        fi
    fi

    for File in $(grep -ril --include=*.scala "override def name:" ../); do
        if [ "$Last" == "$File" ]; then
            Last=None
        fi
        if [ "$Last" == "None" ]; then
            echo $File > $StatusFile
            # Add 'import com.intel.intelanalytics.engine.plugin.{ PluginDoc, ArgDoc }' if necessary
            grep "import com.intel.intelanalytics.engine.plugin.{ PluginDoc, ArgDoc }" $File > /dev/null
            if [ "$?" != "0" ]; then
                echo "import com.intel.intelanalytics.engine.plugin.{ PluginDoc, ArgDoc }" >> $File
            fi
            RST=$(grep -i "override def name:" $File | awk -F= '{print "../doc-api-examples/src/main/resources/python/" $2 ".rst"}' | sed s/:/-/g | sed s/\"//g | sed s/\ //g)
            if [ -e $RST ]; then
                vi $RST $File -c 'sp | n'
                Return=$?
            else
                vi $File
                Return=$?
            fi
            if [ "$Return" != "0" ]; then
                break
            fi
        fi
    done
    echo "Done."
fi
