package com.intel.intelanalytics.domain.graph

import com.intel.intelanalytics.domain.HasId

import org.joda.time.DateTime


/**
 * The metadata entry for a graph.
 * @param id unique id auto-generated by the database
 * @param name name assigned by user, auto-assigned by system if user doesn't supply
 * @param description description of the graph (a good default might say what frames it came from)
 * @param storage name used in physical data store, the HBase table name
 * @param statusId lifecycle status. For example, INIT (building), ACTIVE, DELETED (un-delete possible), DELETE_FINAL (no un-delete), INCOMPLETE (failed construction)
 * @param createdOn date/time this record was created
 * @param modifiedOn date/time this record was last modified
 * @param createdByUserId user who created this row
 * @param modifiedByUserId  user who last modified this row
 */
case class Graph(id: Long,
                 name: String,
                 description: Option[String],
                 storage: String,
                 statusId: Long,
                 createdOn: DateTime,
                 modifiedOn: DateTime,
                 createdByUserId: Option[Long],
                 modifiedByUserId: Option[Long]) extends HasId {
  require(id > 0)
  require(name != null)
  require(name.trim.length > 0)
}
