package com.intel.intelanalytics.domain

import org.joda.time.DateTime

case class DataFrameTemplate(name: String, description: Option[String] = None) {
  require(name != null)
  require(name.trim.length > 0)
}

/**
 * Represents a Big Data Frame
 * @param id unique id auto-generated by the database
 * @param name name assigned by user, auto-assigned by system if user doesn't supply
 * @param description description of frame (a good default description might be the name of the input file)
 * @param uri absolute path to the file backing the frame in HDFS
 * @param schema the schema of the frame (defines columns, etc)
 * @param status lifecycle status. For example, INIT (building), ACTIVE, DELETED (un-delete possible), DELETE_FINAL (no un-delete), INCOMPLETE (failed construction)
 * @param createdOn date/time this record was created
 * @param modifiedOn date/time this record was last modified
 * @param createdBy user who created this row
 * @param modifiedBy user who last modified this row
 */
case class DataFrame(id: Long,
                     name: String,
                     description: Option[String] = None,
                     uri: String,
                     schema: Schema = Schema(),
                     status: Long,
                     createdOn: DateTime,
                     modifiedOn: DateTime,
                     createdBy: Option[Long],
                     modifiedBy: Option[Long]) extends HasId {
  require(id >= 0)
  require(name != null)
  require(name.trim.length > 0)
}
