package com.intel.intelanalytics.domain

import org.joda.time.DateTime

/**
 * An instance of a Hook execution.
 *
 * Every time a Hook callback is attempted a new HookExecution is created whether
 * the result is success or failure.
 *
 * @param id unique id auto-generated by the database identifying this hookExecution
 * @param hookId unique id identifying the hook this execution belongs to
 * @param success true if this hook execution was successful (2xx response code)
 * @param responseCode the HTTP response code received when this hook execution was attempted. -1 means no response code.
 * @param errorBody the body of the HTTP response if an error was received (convenience for debugging purposes)
 * @param createdOn date/time this record was created
 * @param modifiedOn date/time this record was last modified
 */
case class HookExecution(id: Long, hookId: Long, success: Boolean = false, responseCode: Int = -1, errorBody: String, createdOn: DateTime, modifiedOn: DateTime) extends HasId {

}
